[env:motor_controller]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
board_build.core = earlephilhower
board_upload.flash_size = 2097152
board_upload.maximum_size = 2097152
board_build.filesystem_size = 65536
build_type = debug

build_flags =
    -D__PICO_RP2350A=0
    -DSIMPLEFOC_PWM_LOWSIDE_ACTIVE_HIGH=false
    -DHAS_USB_PD=1

build_src_filter = +<*> -<current_test.cpp> -<hello.cpp>

lib_deps =
    askuric/Simple FOC@^2.3.5
    kcl93/FUSB302 PD UFP sink
    adafruit/Adafruit NeoPixel

lib_archive = false

extra_scripts = pre:scripts/patch_libs.py

monitor_speed = 115200
upload_protocol = picotool

[env:hello]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
board_build.core = earlephilhower
board_upload.flash_size = 2097152
build_flags = -D__PICO_RP2350A=0
build_src_filter = +<hello.cpp>
monitor_speed = 115200

[env:current_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
board_build.core = earlephilhower
board_upload.flash_size = 2097152
build_flags = -D__PICO_RP2350A=0
build_src_filter = +<current_test.cpp>
monitor_speed = 115200
upload_protocol = picotool
